### PR TITLE
add component generator for rails

### LINKED ISSUE #75: Component generators for Rails

### PR DESCRIPTION
**Pull request by imella**
Closes #75

### CODE REVIEW

**Comment by joeldrapper** [comment]
Thanks @imella! This looks great. I’m going to try it out.

**Comment by joeldrapper** [comment]
I can’t believe this just works with out a Railtie! So cool!

**Comment by imella** [comment]
> I can’t believe this just works with out a Railtie! So cool!

Really? Hahaha that's a surprise for me too. Nice!

**Comment by alexandreruban** [comment]
I just have a question for this, does it make sense to suffix the class name and the file name with `Component` and `_component.rb`?

```diff
rails g component Navbar

+ # components/navbar.rb
+ class Navbar < Phlex::Component
+ end

- # components/navbar_component.rb
- class NavbarComponent < Phlex::Component
- end
```

What do you think?

**Comment by joeldrapper** [comment]
@alexandreruban I agree. I really like using non-suffixed names within a module, e.g. `Components::NavBar`.

**Pull request merged**
