### PR TITLE
Allow tests to be ran against a single folder

### PR DESCRIPTION
**Pull request by bschrag620**
* adds list_tests executable for echoing a list of files
* updates to github actions yml to leverage list_tests

### CODE REVIEW

**Comment by joeldrapper** [comment]
It's only failing because of Rubocop. Looks like it's running all the tests in each case though. I wonder if we should just try to makes us take a folder, e.g. `bundle exec sus test/rails`. Looks like this is the executable. https://github.com/ioquatix/sus/blob/main/bin/sus

**Comment by bschrag620** [comment]
>  Looks like it's running _all_ the tests in each case though. 

Typo in the command was attempting to run `list_test` instead of `list_tests`

> I wonder if we should just try to make sus take a folder, e.g. `bundle exec sus test/rails`. 

I had tried this locally but got errors that `test/<folder-name>` was a folder.

**Comment by joeldrapper** [comment]
> I had tried this locally but got errors that test/<folder-name> was a folder.

Right, but I mean we could submit a PR to Sus to make this work.

**Comment by bschrag620** [comment]
> Right, but I mean we could submit a PR to Sus to make this work.

Happy to look into that. Latest test suite does look like it properly ran each folder individually. Spot checking the total assertions real quick to make sure tests didn't get skipped.

**Comment by bschrag620** [comment]
So I see a difference of 1 in total test files ran. There is a `rails.rb`  that is directly in `phlex/` which explains the difference.

**Comment by joeldrapper** [comment]
> Happy to look into that.

In the meantime, I should merge this with #212.

**Pull request closed without merging**
