### PR TITLE
Fix CSS generation in the documentation

### LINKED ISSUE #182: CSS is not generated correctly when deploying docs
It's meant to be generated by this line. I’m not sure why it's not working.  https://github.com/joeldrapper/phlex/blob/14b15987efc2e982860905d90b54724e0ff0e02f/docs/build.rb#L22

### PR DESCRIPTION
**Pull request by alexandreruban**
Closes #182

In this PR, we fix the CSS generation in the documentation.

### CODE REVIEW

**Comment by joeldrapper** [comment]
I don't know if this will fix it as the CSS generation doesn't seem to be working correctly locally either. It only seems to work if I delete the `dist` folder.

**Comment by alexandreruban** [comment]
That's strange!
On my side locally, the CSS is successfully updated when running `bundle exec docs/build.rb` multiple times.

For example, if I add this:

```css
/* docs/assets/application.css */

.something {
  @apply text-red-500
}
```

Then run `bundle exec docs/build.rb`, I get the correct result in `docs/dist/application.css`, even if I change the color multiple times and without deleting the `dist` folder.

**Comment by alexandreruban** [comment]
Also, in the latest build on `main`, we have the following warning in the `docs` workflow:

```
Run bundle exec docs/build.rb
  bundle exec docs/build.rb
  shell: /usr/bin/bash -e {0}
npm WARN exec The following package was not found and will be installed: tailwindcss@3.1.8

Done in 237ms.
```

We don't have the warning anymore on this branch: 

```
Run bundle exec docs/build.rb
  bundle exec docs/build.rb
  shell: /usr/bin/bash -e {0}

Done in 273ms.
```

However, I'm not 100% sure it will solve the problem and I'm not sure either how to test it 😄

**Comment by joeldrapper** [comment]
Thanks so much for testing all this. Feel free to merge anything you need to in order to test the deploy task. I think you've got commit permission.

**Review by joeldrapper — APPROVED** [review]

**Comment by joeldrapper** [comment]
Looks like you did it! 🙌

**Comment by alexandreruban** [comment]
Whooh! Happy it worked!! 😄

**Pull request merged**
